# -*- coding: utf-8 -*-
"""Flower_Data_Set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHDc61dYR6bPaxJ4B1g0hC6lk71bta99
"""



import pandas as pd

path="/content/drive/MyDrive/Flower Dataset/Iris.csv"
df=pd.read_csv(path)
df.head(5)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
sns.set(style="darkgrid", color_codes=True)

df["Species"].value_counts()

sns.FacetGrid(df, hue="Species", height=6).map(plt.scatter, "PetalLengthCm", "SepalWidthCm").add_legend()

flower_mapping = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}
df.Species = df['Species'].map(flower_mapping)

df.head()

from sklearn.model_selection import train_test_split

x=df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values
y=df[['Species']].values
x_train, x_test, y_train, y_test = train_test_split(x, y)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train,y_train)

model.score(x_test,y_test)